---
title: "Covid-19 CZ: selected data for the Czech Republic"
---

```{r setup, include=F}

knitr::opts_chunk$set(fig.retina = 3, echo = F, eval = T,
                      warning = F,
                      out.width = "90%",
                      dev = "ragg_png",
                      fig.showtext = T,
                      message = F)

knitr::opts_knit$set()

library(stringr)
library(dplyr)
library(ggplot2)
library(czso)
library(CzechData)
library(lubridate)
library(ragg)
library(ptrr)
library(scales)
library(fontawesome)
library(tidyverse)
library(pragr)
library(ggiraph)
library(rmapshaper)

Sys.setlocale("LC_TIME", "cs_CZ.UTF-8")

ptrr::set_geom_defaults()
update_geom_defaults("rect", list(fill = "blue"))
```

```{r fonts}
sysfonts::font_add_google("IBM Plex Sans", "Roboto")
sysfonts::font_add_google("IBM Plex Sans Condensed", "Roboto Condensed")
```

```{r metathis}
library(metathis)

meta() %>%
  meta_description(
    "Vybraná data o Covid-19 v ČR"
  ) %>% 
  meta_name("github-repo" = "petrbouchal/covid") %>% 
  meta_viewport() %>% 
  meta_social(
    title = "Czech Track",
    url = "https://petrbouchal.github.io/covid/",
    image = "https://petrbouchal.github.io/covid/twitter_card_large.png",
    image_alt = "Náhled grafu nárůstu případů podle okresů",
    og_type = "website",
    og_author = c("Petr Bouchal"),
    twitter_card_type = "summary_large_image",
    twitter_creator = "@petrbouchal"
  )
```

# {.tabset}

## Covid-19 cases overview {.tabset .tabset-pills} 

```{r case-data-load}
cisokr <- czso_get_codelist(109) %>% 
  select(okres_lau_kod = CHODNOTA, okres = ZKRTEXT)
ciskraj <- czso_get_codelist(108) %>% 
  select(kraj_nuts_kod = CHODNOTA, kraj = ZKRTEXT)

nhs <- read_csv("https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/nakaza.csv")

nhs_bd <- read_csv("https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/osoby.csv") %>% 
  left_join(cisokr) %>% 
  left_join(ciskraj)

nhs_okr <- read_csv("https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/kraj-okres-nakazeni-vyleceni-umrti.csv") %>% 
  left_join(cisokr) %>% 
  left_join(ciskraj)

umrti <- read_csv("https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/umrti.csv") %>% 
  left_join(cisokr) %>% 
  left_join(ciskraj)

epis <- read_csv("https://onemocneni-aktualne.mzcr.cz/api/v2/covid-19/kraj-okres-nakazeni-vyleceni-umrti.csv")
```


```{r okresy-geo-load, cache=T}
okresy_p <- CzechData::load_RUIAN_state("okresy") %>%
  ms_simplify(keep = .01, keep_shapes = T)
```

```{r populace}
obyv_praha <- czso_get_table("130141r20") %>% 
  filter(idhod == "830959865") %>% 
  select(hodnota) %>% 
  mutate(okres_lau_kod = "CZ0100")

obyv_okresy <- czso_get_table("130141r20") %>% 
  filter(vuzemi_cis == "101", vuk_text == "Střední stav obyvatel") %>% 
  left_join(czso_get_codelist(101) %>% 
              select(okres_lau_kod = CZNUTS, vuzemi_kod = CHODNOTA)) %>% 
  rows_insert(obyv_praha) %>% 
  rename(pocobyv = hodnota)
```


```{r model, eval=F}
lm_okres <- function(df) {
  lm(kumulativni_pocet_nakazenych ~ as.numeric(datum), data = df)
}

epis %>% 
  group_by(okres_lau_kod) %>% 
  # mutate(kumulativni_pocet_nakazenych = na_if(kumulativni_pocet_nakazenych, 0)) %>% 
  nest() %>% 
  mutate(model = map(data, lm_okres)) %>% 
  mutate(glance = map(model, broom::glance)) %>% 
  unnest(glance) %>%
  # select(-data, -model) %>% 
  ungroup() %>% 
  skimr::skim()
```

```{r weeks, eval = T}
last_week <- today() - period(1, "week")
last_week_fmt <- ptrr::format_date_human(last_week)
```

```{r narust}
nhs_narust <- nhs_bd %>%
  filter(datum >= last_week) %>%
  group_by(okres, okres_lau_kod, datum) %>% 
  summarise(pocet = n(), .groups = "drop") %>% 
  complete(okres, datum, fill = list(pocet = 0)) %>% 
  drop_na(okres) %>%
  left_join(obyv_okresy %>% select(okres_lau_kod, pocobyv)) %>% 
  group_by(okres) %>% 
  filter(sum(pocet) > 5) %>% 
  arrange(okres, datum) %>%
  mutate(narust = cumsum(pocet), narust_perk = narust/pocobyv * 100000) %>% 
  ungroup() %>% 
  mutate(okres = fct_reorder(okres, narust, max, na.rm = T, .desc = T))
```

### Growth by district since `r last_week_fmt`

```{r narust-plot}
nhs_narust %>% 
  filter(max(pocet, na.rm = T) > 0) %>%
  ggplot(aes(datum, narust)) +
  geom_line(colour = "darkblue", size = 1) +
  geom_point(colour = "darkblue", size = 1.5) +
  facet_wrap(facets = vars(okres)) +
  scale_y_continuous(expand = expansion(add = c(60, 60))) +
  scale_x_date(labels = label_date_short(format = c(NA, "%b", "%d", "%h")), 
               breaks = breaks_width("2 days")) +
  ptrr::theme_ptrr("y", multiplot = T) +
  theme(axis.text.x = element_text(hjust = 0))
```


```{r narust-tab, eval=F}
nhs_bd %>% 
  filter(datum > "2020-07-13") %>%
  mutate(okr_grp = fct_lump_n(okres, 10, other_level = "Ostatní")) %>%
  drop_na(okr_grp) %>% 
  count(okr_grp, sort = F) %>% 
  ungroup() %>% 
  mutate(okr_grp = fct_reorder(okr_grp, n, .desc = T) %>% 
           fct_relevel("Ostatní", after = Inf)) %>% 
  arrange(okr_grp)
```


```{r days-since-data}
lastpos <- nhs_bd %>% 
  group_by(okres, okres_lau_kod) %>% 
  summarise(last_pos = max(datum)) %>% 
  mutate(days_since_last = today() - last_pos) %>% 
  arrange(desc(days_since_last))

lastwk <- nhs_bd %>% 
  left_join(obyv_okresy %>% select(okres_lau_kod, pocobyv)) %>% 
  drop_na(okres) %>% 
  filter(datum > last_week) %>% 
  group_by(okres, okres_lau_kod) %>% 
  summarise(pocet = n(), pocobyv = mean(pocobyv), pocet_perk = pocet/pocobyv*1000)
```

### Cases last week

```{r map-cases}
library(patchwork)

okresy_percap_plot <- okresy_p %>% 
  left_join(lastwk, by = c("lau1_kod" = "okres_lau_kod")) %>% 
  drop_na(okres) %>%
  mutate(tooltip = paste0(okres, "\n", label_number_cz(.01)(pocet_perk))) %>% 
  # replace_na(list(pocet = 0)) %>% 
  ggplot(aes(fill = pocet_perk, data_id = lau1_kod, tooltip = tooltip)) +
  geom_sf_interactive(colour = NA) +
  scale_fill_binned(na.value = "grey", n.breaks = 6,
                    labels = label_number_cz(accuracy = .01),
                    type = scale_fill_viridis_c, option = "D",
                    limits = c(min(lastwk$pocet_perk), max(lastwk$pocet_perk))) +
  guides(fill = guide_bins(title = NULL, direction = "vertical", override.aes = list(colour = NA),
                           show.limits = T, ticks = F, even.steps = T, axis = T, reverse = F)) +
  theme_void() +
  theme(legend.position = "right", legend.justification = 0) +
  labs(title = "Počet nových případů za posledních 7 dní",
       subtitle = "Na 100 tisíc obyvatel")

okresy_abs_plot <- okresy_p %>% 
  left_join(lastwk, by = c("lau1_kod" = "okres_lau_kod")) %>% 
  drop_na(okres) %>%
  mutate(tooltip = paste0(okres, "\n", label_number_cz(1)(pocet))) %>% 
  # replace_na(list(pocet = 0)) %>% 
  ggplot(aes(fill = pocet, data_id = lau1_kod, tooltip = tooltip)) +
  geom_sf_interactive(colour = NA) +
  scale_fill_binned(na.value = "grey", n.breaks = 7,
                    labels = label_number_cz(accuracy = 1),
                    limits = c(min(lastwk$pocet), max(lastwk$pocet)),
                    type = scale_fill_viridis_c, option = "D"
                    ) +
  guides(fill = guide_bins(title = NULL, direction = "vertical", 
                           override.aes = list(colour = NA),
                           show.limits = T, ticks = F, even.steps = T, axis = T, reverse = F)) +
  theme_void() +
  theme(legend.position = "right", legend.justification = 0) +
  labs(subtitle = "Absolutně")

girafe(code = print(okresy_percap_plot / okresy_abs_plot), fonts = list(sans = "IBM Plex Sans"), 
       options = list(opts_sizing(width = 1),
                      opts_tooltip(css = "font-family: IBM Plex Sans; color:white; background-color: black; padding:6px;border-radius:5px;"),
                      opts_hover(css = "stroke: white")))
```


```{r age, eval=F}
nhs_bd %>% 
  mutate(vek_cat = cut(vek, breaks = c(0, 15, 30, 65, 85, Inf))) %>% 
  count(kraj, vek_cat) %>% 
  ggplot(aes(n, kraj)) +
  geom_col(aes(fill = vek_cat), position = "fill")
```


```{r age-deaths, eval=F}
umrti %>% 
  mutate(vek_cat = cut(vek, breaks = c(0, 15, 30, 65, 85, Inf))) %>% 
  count(kraj, vek_cat) %>% 
  ggplot(aes(n, kraj)) +
  geom_col(aes(fill = vek_cat), position = "fill")
```

### Days since last case in each district

```{r map-days-since}
lastpos_ch <- okresy_p %>% 
  left_join(lastpos, by = c("lau1_kod" = "okres_lau_kod")) %>% 
  drop_na(okres)

lastpos_g <- ggplot(lastpos_ch, aes(fill = as.integer(days_since_last))) +
  geom_sf_interactive(aes(data_id = okres, tooltip = paste0(okres, "\n", days_since_last))) +
  scale_fill_binned(na.value = "grey", show.limits = T, n.breaks = 6,
                    type = "viridis",
                    limits = c(min(lastpos_ch$days_since_last),
                               max(lastpos_ch$days_since_last)) %>%
                      as.integer()) +
  guides(fill = guide_coloursteps(even.steps = F,
                                  title = NULL, direction = "horizontal",
                                  show.limits = T, ticks = F)) +
  theme_void() +
  theme(legend.position = c(.8, .8))

girafe(ggobj = lastpos_g, fonts = list(sans = "IBM Plex Sans"), 
       options = list(opts_sizing(width = 1),
                      opts_tooltip(css = "font-family: IBM Plex Sans; color:white; background-color: black; padding:6px;border-radius:5px;"),
                      opts_hover(css = "stroke: white")))
```


## Mortality statistics {.tabset .tabset-pills}

```{r mort-data}
zmr0 <- czso_get_table("130185", force_redownload = T)
zmr <- zmr0 %>% 
  mutate(tyden = as.numeric(tyden),
         casref_do = as.Date(casref_do),
         day_sameyear = make_date(1970, month = month(casref_do),
                                  day = day(casref_do)))  

last_date_fmt <- ptrr::format_date_human(max(zmr$casref_do))
today_fmt <- ptrr::format_date_human()
```


```{r mort-base}
zemr_plot_base <- zmr %>% 
  ggplot(aes(day_sameyear, hodnota,
             alpha = rok == 2020, size = rok == 2020)) +
  geom_line(aes(colour = as.factor(rok), group = rok)) +
  scale_alpha_manual(values = c(`TRUE` = 1, `FALSE` = .4), guide = "none") +
  scale_size_manual(values = c(`TRUE` = .7, `FALSE` = .4), guide = "none") +
  scale_colour_viridis_d(direction = -1, name = "rok") +
  ptrr::theme_ptrr("both", multiplot = T, axis.title.x = element_text()) +
  labs(x = "Týden v roce",
       subtitle = str_glue("Poslední data k {last_date_fmt}, staženo {today_fmt}"),
       title = "Počty zemřelých podle týdnů v roce, 2011-2020",
       caption = "Data: ČSÚ, sada 130185 | @petrbouchal") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b", breaks = c(1,3,6, 9, 12)) +
  theme(axis.text.x = element_text(hjust = 0))
```

### Fixed axes (Full comparison)

```{r mort-plot-fixed}
zemr_plot_base +
  facet_wrap(~vek_txt)
```

### Detail (separate axes)

```{r mort-plot-free}
zemr_plot_base +
  facet_wrap(~vek_txt, scales = "free_y")
```


# 

Last built on `r format(lubridate::now("CET"), "%Y-%m-%d %H:%M %Z")`
