name: Render and Deploy RMarkdown Website
'on': 
  push:
  schedule:
    - cron:  '10 7 * * *'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      # - name: Install locale
      #   run: locale-gen cs_CZ.UTF-8
      
      - name: Install XQuartz on MacOS
        if: runner.os == 'macOS'
        run: brew cask install xquartz
      
      - name: Install cairo
        if: runner.os == 'macOS'
        run: brew install cairo

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' # The pandoc version to download (if necessary) and use.

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install packages
        env: 
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Render Site
        run: |-
          Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
     
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
